name: Documentation
title: "Documentation: "
description: "This issue is about a documentation suggestion or error."
labels: ["Issue: Documentation", "Status: Pending..."]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      description: "A quick checklist to ensure something something yadi yada"
      options:
        - label: "I checked and searched if this issue/suggestion has already been reported in this repo."
    validations:
      required: true
