name: Build

on:
  push:
  workflow_dispatch:

jobs:
  buildWindows:
    name: Build Windows Application
    runs-on: windows-latest

    steps:
      - name: Download Source Code
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Install Haxe Libraries using HxPKG
        run: |
          haxelib install hxcpp --quiet
          haxelib install hxpkg --quiet
          haxelib run hxpkg install --force

      - name: Compile Application
        run: haxelib run lime build windows

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TechNotDrip-Engine_WINDOWS
          path: export/release/windows/bin/

  buildMacOS:
    name: Build MacOS Application
    runs-on: macos-latest

    steps:
      - name: Download Source Code
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Install Haxe Libraries using HxPKG
        run: |
          haxelib install hxcpp --quiet
          haxelib install hxpkg --quiet
          haxelib run hxpkg install --force

      - name: Compile Application
        run: haxelib run lime build macos

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TechNotDrip-Engine_MACOS
          path: export/release/macos/bin/

  buildLinux:
    name: Build Linux Application
    runs-on: ubuntu-latest

    steps:
      - name: Download Source Code
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Install Haxe Libraries using HxPKG
        run: |
          sudo apt install libvlccore-dev libvlc-dev -y -q
          haxelib install hxcpp --quiet
          haxelib install hxpkg --quiet
          haxelib run hxpkg install --force

      - name: Compile Application
        run: haxelib run lime build linux

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TechNotDrip-Engine_LINUX
          path: export/release/linux/bin/

  buildAndroid:
    name: Build Android Application
    runs-on: ubuntu-latest

    steps:
      - name: Download Source Code
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: ndk
        with:
          ndk-version: r21e

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Install Haxe Libraries using HxPKG
        run: |
          sudo apt install libvlccore-dev libvlc-dev -y -q
          haxelib install hxcpp --quiet
          haxelib install hxpkg --quiet
          haxelib run hxpkg install --force

      - name: Configure Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT ${{ steps.ndk.outputs.ndk-path }}
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true

      - name: Compile Application
        run: haxelib run lime build android

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TechNotDrip-Engine_ANDROID
          path: export/release/android/bin/app/build/outputs/apk/debug/*.apk

  buildiOS:
    name: Build iOS Application
    runs-on: macos-latest

    steps:
      - name: Download Source Code
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Install Haxe Libraries using HxPKG
        run: |
          haxelib install hxcpp --quiet
          haxelib install hxpkg --quiet
          haxelib run hxpkg install --force

      - name: Compile Application
        run: haxelib run lime build ios -nosign

      - name: Zip up IPA File
        run: |
          cd export/release/ios/build/Release-iphoneos
          mkdir Payload
          mv *.app Payload
          zip -r TechNotDrip.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TechNotDrip-Engine_IOS
          path: export/release/ios/build/Release-iphoneos/*.ipa
